#!/bin/sh
set -x
SERVER="$1"

scp ./config/* $SERVER:~
ssh -t $SERVER "
set -x
cd /etc
[ -d /etc/.git ] || sudo git init
sudo git add /etc/condor/condor_config.local
sudo git commit -m 'Configuración original de debian para condor

- /etc/condor/condor_config.local'

sudo cp ~/etc-condor-condor-config.d-00hostname /etc/condor/config.d/00\$(hostname)
sudo cp ~/etc-condor-condor_config.local /etc/condor/condor_config.local
sudo git commit -m \"Agregar \$(hostname) al cluster de condor.\"
systemctl status condor && sudo systemctl restart condor || sudo systemctl start condor
"